project:
  type: website

website:
  title: "LinoSergio.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



