project:
  type: website

website:
  title: "Lino Sergio Rocha Conceição"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: superhero
    css: styles.css
    toc: true



